export const RegisterActionTypes = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_CURRENT_USER_PENDING : 'SET_CURRENT_USER_PENDING',

    GET_PROFILE : 'GET_PROFILE',
    

    LOGOUT: 'USERS_LOGOUT',
}