export const PostActionTypes = {
    FETCH_POST_PENDING : 'FETCH_POST_PENDING',
    FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
    FETCH_POST_ERROR : 'FETCH_POST_ERROR',

    FETCH_TAG_POSTS_PENDING : 'FETCH_TAG_POSTS_PENDING',
    FETCH_TAG_POSTS_SUCCESS : 'FETCH_TAG_POSTS_SUCCESS',
    FETCH_TAG_POSTS_FAILURE : 'FETCH_TAG_POSTS_FAILURE',


    FETCH_POST_DETAIL_PENDING: ' FETCH_POST_DETAIL_PENDING',
    FETCH_POST_DETAIL_SUCCESS : 'FETCH_POST_DETAIL_SUCCESS',
    FETCH_POST_DETAIL_FAILURE : 'FETCH_POST_DETAIL_FAILURE',

    FETCH_FOLLOWED_USER_POSTS_SUCCESS: 'FETCH_FOLLOWED_USER_POSTS_SUCCESS',


    LIKE_POST : 'LIKE_POST',
    UNLIKE_POST: 'UNLIKE_POST',
    LIKE_ERROR: 'LIKE_ERROR',
    LIKE_ALREADY: 'LIKE_ALREADY',
    LIKE_PENDING: 'LIKE_PENDING',


    COMMENT_PENDING: 'COMMENT_PENDING',
    COMMENT_SUCCESS: 'COMMENT_SUCCESS',
    COMMENT_FAILURE: 'COMMENT_FAILURE'


}