export const updateProfileActionTypes = {
    UPDATE_PROFILE_PENDING : 'UPDATE_PROFILE_PENDING',
    UPDATE_PROFILE_SUCCESS : 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILED : 'UPDATE_PROFILE_FAILED'
    }

    