export const followUserActionTypes = {
    GET_FOLLOW_USER_PENDING : 'GET_FOLLOW_USER_PENDING',
    GET_FOLLOW_USER_SUCCESS : 'GET_FOLLOW_USER_SUCCESS',
    GET_FOLLOW_USER_ERROR : 'GET_FOLLOW_USER_ERROR',


    FOLLOW_USER_PENDING : 'FOLLOW_USER_PENDING',
    FOLLOW_USER_SUCCESS : 'FOLLOW_USER_SUCCESS',
    FOLLOW_USER_ERROR : 'FOLLOW_USER_ERROR'


}