export const followUserPostsActionTypes = {
    FOLLOW_USER_POSTS_PENDING : 'FOLLOW_USER_POSTS_PENDING',
    FOLLOW_USER_POSTS_SUCCESS : 'FOLLOW_USER_POSTS_SUCCESS',
    FOLLOW_USER_POSTS_FAILURE : 'FOLLOW_USER_POSTS_FAILURE'
}