export const UserActionTypes = {
    LOGIN_USER : 'LOGIN_USER',
    REMOVE_USER: 'REMOVE_USER',
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    ERROR: 'ERROR',
    UPDATE_USER_PROFILE_DETAIL: 'UPDATE_USER_PROFILE_DETAIL',
    UPDATE_USER_PROFILE_FAILED: 'UPDATE_USER_PROFILE_FAILED',
    UPLOAD_IMAGE_SUCCESSFUL: 'UPLOAD_IMAGE_SUCCESSFUL'
}